name: Skill Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements-dev.txt
    
    - name: Run validation tests
      run: |
        python validate.py
        python scripts/validate_skill.py
    
    - name: Run linting
      run: |
        flake8 __init__.py --max-line-length=120
    
    - name: Run unit tests
      run: |
        python scripts/dev_utils.py test